version: '3'

services:
  web:
    build: web/
    volumes:
      - ./web/:/app/
    labels:
      - traefik.http.routers.web.rule=PathPrefix(`/`)

  auth:
    build: auth/
    volumes: 
      - ./auth/:/app/
    labels:
      - traefik.http.routers.auth.rule=PathPrefix(`/auth/`)
      - traefik.http.middlewares.auth.forwardauth.address=https://localhost/auth

  exams:
    build: exams/
    volumes:
      - ./exams/:/app/
    labels:
      - traefik.http.routers.exams.rule=Host(`exam.localhost`)

  main:
    build: main/
    volumes:
      - ./main:/app/
    labels:
      - traefik.http.routers.main.rule=Host(`api.localhost`)

  postgres:
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: classroom
    volumes:
      - classroom-postgres:/var/lib/postgresql/data
  
  mongo:
    image: mongo:5.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: classroom
    volumes:
      - classroom-mongo:/data/db

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  traefik:
    image: traefik:2.4
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



volumes:
    classroom-postgres:
      external: false
    classroom-mongo:
      external: false
