version: '3'

services:
  web:
    build: web/
    volumes:
      - ./web/:/app/
    command: npm run dev
    labels:
      - traefik.http.routers.web.rule=PathPrefix(`/`)

  auth:
    build:
      dockerfile: docker/development/Dockerfile
      context: auth/
    volumes:
      - ./auth/:/app/
    expose:
      - "${AUTH_SERVICE_PORT}"
    labels:
      - traefik.http.middlewares.auth.forwardauth.address=http://localhost/auth/
      - traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Auth-User,X-Auth-User-Email"
      - traefik.http.routers.auth.rule=PathPrefix(`/auth`)

  exams:
    build: exams/
    volumes:
      - ./exams/:/app/
    expose:
      - "${EXAMS_SERVICE_PORT}"
    labels:
      - traefik.http.routers.exams.rule=PathPrefix(`/exams`)

  main:
    build:
      dockerfile: docker/app/development/Dockerfile
      context: ./main/
    volumes:
      - ./main:/app/
    expose:
      - "${MAIN_SERVICE_PORT}"
    labels:
      - traefik.http.routers.main.rule=PathPrefix(`/api`)
      - traefik.http.routers.main.middlewares=auth

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: classroom
    volumes:
      - classroom-postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: classroom
    volumes:
      - classroom-mongo:/data/db

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  traefik:
    image: traefik:2.4
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio-volume:/data
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123

  auth-docs:
    build:
      dockerfile: docker/development/Dockerfile
      context: auth/
    volumes:
      - ./auth/:/app/
    command: [ "air", "-c", ".air.toml", "--", "docs:serve" ]
    expose:
      - 80
    labels:
      - traefik.http.routers.auth-docs.rule=PathPrefix(`/docs/auth`)

  main-docs:
    build:
      dockerfile: docker/docs/development/Dockerfile
      context: main/
    volumes:
      - ./main:/app/
      - ./main/docker/docs/development/.air.toml:/app/.air.toml
    expose:
      - 80
    labels:
      - traefik.http.routers.main-docs.rule=PathPrefix(`/docs/main`)

volumes:
  classroom-postgres:
    external: false
  classroom-mongo:
    external: false
  minio-volume:
    external: false
