version: '3'

services:
  web:
    build: web/
    volumes:
      - ./web/:/app/
    command: npm run dev
    labels:
      - traefik.http.routers.web.rule=PathPrefix(`/`)

  auth:
    build: 
      dockerfile: docker/development/Dockerfile
      context: auth/
    volumes: 
      - ./auth/:/app/
    expose:
      - "${AUTH_SERVICE_PORT}"
    labels:
      - traefik.http.middlewares.auth.forwardauth.address=http://localhost/auth/
      - traefik.http.routers.auth.rule=Host(`auth.localhost`)
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeadersRegex=^X-"

  exams:
    build: exams/
    volumes:
      - ./exams/:/app/
    expose:
      - "${EXAMS_SERVICE_PORT}"
    labels:
      - traefik.http.routers.exams.rule=Host(`exams.localhost`)

  main:
    build: 
      dockerfile: docker/development/Dockerfile
      context: ./main
    volumes:
      - ./main:/app/
    expose:
      - "${MAIN_SERVICE_PORT}"
    labels:
      - traefik.http.routers.main.rule=Host(`main.localhost`)
      - traefik.http.routers.main.middlewares=auth
      - "traefik.http.middlewares.main.forwardauth.authResponseHeadersRegex=^X-"

  postgres:
    image: postgres:12
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: classroom
    volumes:
      - classroom-postgres:/var/lib/postgresql/data
  
  mongo:
    image: mongo:5.0.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: classroom
    volumes:
      - classroom-mongo:/data/db

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  traefik:
    image: traefik:2.4
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./s3/data/:/data
    ports:
      - 9001:9001
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: access
      MINIO_SECRET_KEY: secret123

# DOCUMENTATION

  auth-docs:
    build: 
      dockerfile: auth/docker/development/Dockerfile
      context: auth/
    volumes: 
      - ./auth/:/app/
    command: ["air", "-c", ".air.toml", "--", "docs:serve"]
    expose:
      - 80
    labels:
      - traefik.http.routers.auth-docs.rule=Host(`docs.auth.localhost`)

  main-docs:
    build: 
      dockerfile: main/docker/development/Dockerfile
      context: .
    volumes:
      - ./main:/app/
    expose:
      - 80
    command: ["air", "-c", ".air.toml", "--", "docs:serve"] 
    labels:
      - traefik.http.routers.main-docs.rule=Host(`docs.main.localhost`)

volumes:
    classroom-postgres:
      external: false
    classroom-mongo:
      external: false


